# Generated by Django 3.0 on 2020-10-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
