# Generated by Django 3.0 on 2020-10-13 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_auto_20201013_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toy',
            name='release_data',
        ),
    ]
